### ISSUE TITLE
Can't Reproduce Example

### ISSUE THREAD

**Issue by SauravMaheshkar** [vballoli/vit-flax#3]
The following Traceback was encountered while attempting to reproduce.

```
Traceback (most recent call last):
  File "cifar_train.py", line 83, in <module>
    app.run(main)
  File "/opt/venv/lib/python3.7/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/opt/venv/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "cifar_train.py", line 78, in main
    config.num_epochs)
  File "/home/jovyan/work/vit-flax/examples/train/utils.py", line 500, in train
    summary_writer)
  File "/home/jovyan/work/vit-flax/examples/train/utils.py", line 427, in train_for_one_epoch
    optimizer, state, batch, sharded_keys)
  File "/opt/venv/lib/python3.7/site-packages/jax/traceback_util.py", line 133, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/jax/api.py", line 1536, in f_pmapped
    name=flat_fun.__name__, donated_invars=tuple(donated_invars))
  File "/opt/venv/lib/python3.7/site-packages/jax/core.py", line 1202, in bind
    return call_bind(self, fun, *args, **params)
  File "/opt/venv/lib/python3.7/site-packages/jax/core.py", line 1168, in call_bind
    outs = primitive.process(top_trace, fun, tracers, params)
  File "/opt/venv/lib/python3.7/site-packages/jax/core.py", line 1205, in process
    return trace.process_map(self, fun, tracers, params)
  File "/opt/venv/lib/python3.7/site-packages/jax/core.py", line 579, in process_call
    return primitive.impl(f, *tracers, **params)
  File "/opt/venv/lib/python3.7/site-packages/jax/interpreters/pxla.py", line 499, in xla_pmap_impl
    donated_invars, *abstract_args)
  File "/opt/venv/lib/python3.7/site-packages/jax/linear_util.py", line 251, in memoized_fun
    ans = call(fun, *args)
  File "/opt/venv/lib/python3.7/site-packages/jax/interpreters/pxla.py", line 549, in parallel_callable
    jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(fun, sharded_avals)
  File "/opt/venv/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1193, in trace_to_jaxpr_final
    jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
  File "/opt/venv/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 1174, in trace_to_subjaxpr_dynamic
    ans = fun.call_wrapped(*in_tracers)
  File "/opt/venv/lib/python3.7/site-packages/jax/linear_util.py", line 160, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/jovyan/work/vit-flax/examples/train/utils.py", line 290, in train_step
    (_, (new_state, logits)), grad = grad_fn(optimizer.target)
  File "/opt/venv/lib/python3.7/site-packages/jax/traceback_util.py", line 133, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/jax/api.py", line 817, in value_and_grad_f
    ans, vjp_py, aux = _vjp(f_partial, *dyn_args, has_aux=True)
  File "/opt/venv/lib/python3.7/site-packages/jax/api.py", line 1851, in _vjp
    out_primal, out_vjp, aux = ad.vjp(flat_fun, primals_flat, has_aux=True)
  File "/opt/venv/lib/python3.7/site-packages/jax/interpreters/ad.py", line 115, in vjp
    out_primals, pvals, jaxpr, consts, aux = linearize(traceable, *primals, has_aux=True)
  File "/opt/venv/lib/python3.7/site-packages/jax/interpreters/ad.py", line 100, in linearize
    jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
  File "/opt/venv/lib/python3.7/site-packages/jax/interpreters/partial_eval.py", line 484, in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
  File "/opt/venv/lib/python3.7/site-packages/jax/linear_util.py", line 160, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/jovyan/work/vit-flax/examples/train/utils.py", line 275, in forward_and_loss
    with flax.nn.stateful(state) as new_state:
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/venv/lib/python3.7/site-packages/flax/nn/base.py", line 874, in stateful
    with state.mutate() as new_state:
AttributeError: 'dict' object has no attribute 'mutate'
```

# Steps Followed
I just ran `python cifar_train.py ----model_dir=$MODEL_DIR` after cloning

**Comment by vballoli** [comment]
Yeah sorry even I noticed it, just adopted the code from the flax repository. It'd be of immense help if you could send a PR fixing this. I'll probably take time to fix it.
